name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build-win64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: msys2/setup-msys2@v2
        with:
          install: make mingw-w64-x86_64-gcc mingw-w64-x86_64-{cmake,SDL2,glew,qt5-static}
      - name: Build NanoBoyAdvance
        run: |
          cmake \
            -B build \
            -G "Unix Makefiles" \
            -DCMAKE_CXX_FLAGS="-s" \
            -DCMAKE_EXE_LINKER_FLAGS="-static-libgcc -static-libstdc++" \
            -DSDL2_STATIC=ON \
            -DGLEW_USE_STATIC_LIBS=ON \
            -DCMAKE_BUILD_TYPE=Release
          cd build
          make -j$NUMBER_OF_PROCESSORS
      - name: Collect artifacts
        run: |
          mkdir upload
          cp -r $(which libwinpthread-1.dll) build/bin/sdl/{NanoBoyAdvance.exe,{config,keymap}.toml} upload
          cp -r build/bin/sdl/shader upload/shader
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: NanoBoyAdvance-win64
          path: upload
          if-no-files-found: error

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup SDL2 and GLEW
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y libsdl2-dev libglew-dev qt5-default
      - name: Build NanoBoyAdvance
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cd build
          make -j$(nproc)
      - name: Collect artifacts
        run: |
          mkdir upload
          cp -r build/bin/sdl/{NanoBoyAdvance,{config,keymap}.toml} upload
          cp -r build/bin/sdl/shader upload/shader
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: NanoBoyAdvance-linux
          path: upload
          if-no-files-found: error

  build-macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup SDL2 and GLEW
        env:
          HOMEBREW_NO_ANALYTICS: 1
        run: brew install sdl2 glew qt@5
      - name: Build NanoBoyAdvance
        run: |
          export CPPFLAGS="$CPPFLAGS -I/usr/local/opt/glew/include"
          cmake -B build \
                -DCMAKE_CXX_FLAGS="-s" \
                -DSDL2_STATIC=ON \
                -DGLEW_USE_STATIC_LIBS=ON \
                -DCMAKE_BUILD_TYPE=Release
          cd build
          make -j$(sysctl -n hw.availcpu)
      - name: Collect artifacts
        run: |
          mkdir upload
          cp -r build/bin/sdl/{NanoBoyAdvance,{config,keymap}.toml} upload
          cp -r build/bin/sdl/shader upload/shader
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: NanoBoyAdvance-${{ runner.os }}
          path: upload
          if-no-files-found: error
