name: Build

on: push

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: cmd

    env:
      SET_VC_VARS: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          submodules: recursive
      - name: Setup Qt
        run: |
          curl -L -C - -O https://github.com/ComplexRobot/Qt5-MSVC-Static/releases/download/qt5.15.16/qt5.15.16-msvc-x64-static.7z
          md Qt
          7z x qt5.15.16-msvc-x64-static.7z -oQt
          echo ^<Project^> > Directory.Build.props
          echo   ^<PropertyGroup^> >> Directory.Build.props
          echo     ^<QtInstallDir^>${{ github.workspace }}\Qt\5.15.16\msvc2022-x64-static\^</QtInstallDir^> >> Directory.Build.props
          echo   ^</PropertyGroup^> >> Directory.Build.props
          echo ^</Project^> >> Directory.Build.props
      - name: Build Solution
        id: build
        run: |
          call "%SET_VC_VARS%"
          if "${{ github.ref_name }}"=="master" (
            msbuild NanoBoyAdvance.sln /p:Configuration=Release-Build /p:Platform=x64 /m /v:minimal /nologo
            echo tag-name=v1.8.2ex >> "%GITHUB_OUTPUT%"
            echo make-latest=true >> "%GITHUB_OUTPUT%"
          ) else (
            msbuild NanoBoyAdvance.sln /p:Configuration=Release /p:Platform=x64 /m /v:minimal /nologo
            echo tag-name=${{ github.ref_name }}-%GITHUB_SHA:~0,7% >> "%GITHUB_OUTPUT%"
            echo make-latest=false >> "%GITHUB_OUTPUT%"
          )
      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/Release/*.exe
            build/Release-Build/*.exe
          tag_name: ${{ steps.build.outputs.tag-name }}
          body_path: RELEASE_NOTES.MD
          target_commitish: ${{ github.ref }}
          make_latest: ${{ steps.build.outputs.make-latest }}